
package com.example.userProfile.soap.userService;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "GeneralException", targetNamespace = "http://service.userService.example.com/")
public class GeneralException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private GeneralException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public GeneralException_Exception(String message, GeneralException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public GeneralException_Exception(String message, GeneralException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.example.userProfile.soap.userService.GeneralException
     */
    public GeneralException getFaultInfo() {
        return faultInfo;
    }

}
