
package com.example.profileService.soap.userService;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebService(name = "UserSoapService", targetNamespace = "http://service.userService.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserSoapService {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "publish", targetNamespace = "http://service.userService.example.com/", className = "com.example.profileService.soap.userService.Publish")
    @ResponseWrapper(localName = "publishResponse", targetNamespace = "http://service.userService.example.com/", className = "com.example.profileService.soap.userService.PublishResponse")
    @Action(input = "http://service.userService.example.com/UserSoapService/publishRequest", output = "http://service.userService.example.com/UserSoapService/publishResponse")
    public void publish();

    /**
     * 
     * @param email
     * @return
     *     returns com.example.profileService.soap.userService.UserResponse
     * @throws GeneralException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserByEmail", targetNamespace = "http://service.userService.example.com/", className = "com.example.profileService.soap.userService.GetUserByEmail")
    @ResponseWrapper(localName = "getUserByEmailResponse", targetNamespace = "http://service.userService.example.com/", className = "com.example.profileService.soap.userService.GetUserByEmailResponse")
    @Action(input = "http://service.userService.example.com/UserSoapService/getUserByEmailRequest", output = "http://service.userService.example.com/UserSoapService/getUserByEmailResponse", fault = {
        @FaultAction(className = GeneralException_Exception.class, value = "http://service.userService.example.com/UserSoapService/getUserByEmail/Fault/GeneralException")
    })
    public UserResponse getUserByEmail(
        @WebParam(name = "email", targetNamespace = "")
        String email)
        throws GeneralException_Exception
    ;

    /**
     * 
     * @param userId
     * @return
     *     returns com.example.profileService.soap.userService.UserResponse
     * @throws GeneralException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserById", targetNamespace = "http://service.userService.example.com/", className = "com.example.profileService.soap.userService.GetUserById")
    @ResponseWrapper(localName = "getUserByIdResponse", targetNamespace = "http://service.userService.example.com/", className = "com.example.profileService.soap.userService.GetUserByIdResponse")
    @Action(input = "http://service.userService.example.com/UserSoapService/getUserByIdRequest", output = "http://service.userService.example.com/UserSoapService/getUserByIdResponse", fault = {
        @FaultAction(className = GeneralException_Exception.class, value = "http://service.userService.example.com/UserSoapService/getUserById/Fault/GeneralException")
    })
    public UserResponse getUserById(
        @WebParam(name = "userId", targetNamespace = "")
        Long userId)
        throws GeneralException_Exception
    ;

}
